name: Daily Run and Manual Trigger

on:
  schedule:
    # Runs at midnight UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install Bun
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      # Verify Bun installation
      - name: Verify Bun
        run: bun --version

      # Install dependencies
      - name: Install Dependencies
        run: bun install

      # Run the script
      - name: Execute Script
        run: bun run index.js
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          NGROK_SUBDOMAIN: ${{ secrets.NGROK_SUBDOMAIN }}
          FELT_API_KEY: ${{ secrets.FELT_API_KEY }}
          FELT_MAP_ID: ${{ secrets.FELT_MAP_ID }}